#!/bin/bash
# Generated by /sweep:epic-advance for epic {{EPIC_KEY}} at {{ISO_TS}}
# Run: bash let-it-rip.sh        — execute dispatch
#      bash let-it-rip.sh --dry-run  — print claude -p invocations without executing

set -u
RUN_DIR="$(cd "$(dirname "$0")" && pwd)"
MANIFEST="$RUN_DIR/manifest.json"
DRY_RUN=0
ALWAYS_CLARIFY={{ALWAYS_CLARIFY}}   # baked at skill-time; runtime override below
CONVERGE={{CONVERGE}}               # baked at skill-time; runtime override below
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --always-clarify) ALWAYS_CLARIFY=true ;;
    --converge) CONVERGE=true ;;
    --no-converge) CONVERGE=false ;;
  esac
done

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$RUN_DIR/run.log"; }

update_status() {
  local key=$1 state=$2 extra=${3:-}
  local f="$RUN_DIR/$key/status.md"
  local ts="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  case "$state" in
    running) sed -i.bak "s/^state:.*/state: running/; s/^started_at:.*/started_at: $ts/" "$f" ;;
    done|failed)
      sed -i.bak "s/^state:.*/state: $state/; s/^ended_at:.*/ended_at: $ts/" "$f"
      [[ -n "$extra" ]] && sed -i.bak "s|^delegate_run_dir:.*|delegate_run_dir: $extra|" "$f"
      ;;
  esac
  rm -f "$f.bak"
}

# Build the prompt for a given delegate + ticket-list + tranche.
# Takes ticket_keys (for manifest lookups + per-item-dir resolution); the
# delegate_args fed into the prompt are resolved from the manifest. They differ
# for MR-targeting delegates (delegate_args = "#<iid>", ticket_key = "PROJ-<n>").
build_prompt() {
  local delegate=$1; shift
  local tranche=$1; shift
  local ticket_keys=("$@")

  # Resolve delegate_args ordered the same as ticket_keys.
  local delegate_args=()
  local key
  for key in "${ticket_keys[@]}"; do
    local arg
    arg=$(jq -r --arg k "$key" \
      '.active[] | select(.ticket_key == $k) | .delegate_args[0]' "$MANIFEST")
    delegate_args+=("$arg")
  done

  case "$delegate" in
    sweep:address-prs|sweep:review-prs)
      cat <<EOF
Run /$delegate ${delegate_args[*]}

After it generates its run dir (you'll see "Artifacts written to <PATH>"), run:
  bash <PATH>/let-it-rip.sh

Then capture the <PATH> and report it back as the last line of your output, prefixed with DELEGATE_RUN_DIR=.
EOF
      ;;

    director)
      # Aggregated review+address loop. delegate_args is the MR-IID list
      # (#139 #140 ...) — pass as a comma-separated --prs= for /director.
      local prs_csv
      prs_csv=$(IFS=,; echo "${delegate_args[*]}")
      cat <<EOF
Run /director review+address --converge --prs=$prs_csv

/director will own the convergence loop (review → address → review → ... until its sweep-mode convergence rule fires). When /director exits, capture the session directory it created (typically tmp/claude-artifacts/director-sessions/<timestamp>/) and report it as the last line of your output, prefixed with DELEGATE_RUN_DIR=.
EOF
      ;;

    sweep:work-items)
      # Build directive lines for stacked tickets in this tranche-group.
      # NOTE: never name the per-item directory (e.g. `issue-$key/` or `pr-$key/`)
      # in the directive payload — that path convention is sweep:work-items's
      # internal choice (it uses `issue-<id-or-key>/` for every role; `pr-<N>/`
      # is a different skill's convention), so don't hardcode or assume it here.
      # Naming a path also implicitly hints a role to the parent assessor and
      # bypasses sweep:work-items's conversation-stage gate. Phrase the
      # instruction so the parent resolves the actual per-item dir at runtime
      # from sweep:work-items's manifest.
      local directive_block=""
      for key in "${ticket_keys[@]}"; do
        local stack_text
        stack_text=$(jq -r --arg k "$key" \
          '.active[] | select(.ticket_key == $k) | .stacking.auto_flag_text // empty' "$MANIFEST")
        if [[ -n "$stack_text" ]]; then
          directive_block+="
After /sweep:work-items generates its run dir and per-item directories, but BEFORE running its let-it-rip.sh:

Locate the per-item directory it created for $key (read its manifest.json — the directory naming is sweep:work-items's internal choice; do not assume \`issue-\` or \`pr-\`). Write a \`directives.md\` file inside that directory with this content:

\`\`\`
Stacking directive for $key:

When creating the MR description, include this section at the bottom:

## Stack
$stack_text
\`\`\`
"
        fi
      done

      # Build --dor-ready=KEY1,KEY2 listing the tickets in this group whose DoR
      # verdict is `implement`. sweep:work-items uses this to skip its always-clarify
      # gate for those keys and apply the stage-3 decision rule directly. Suppressed
      # when ALWAYS_CLARIFY=true.
      local dor_ready_flag=""
      if [[ "${ALWAYS_CLARIFY:-false}" != "true" ]]; then
        local dor_ready_keys=""
        for key in "${ticket_keys[@]}"; do
          local verdict
          verdict=$(jq -r --arg k "$key" \
            '.active[] | select(.ticket_key == $k) | .dor.verdict // empty' "$MANIFEST")
          if [[ "$verdict" == "implement" ]]; then
            [[ -n "$dor_ready_keys" ]] && dor_ready_keys+=","
            dor_ready_keys+="$key"
          fi
        done
        [[ -n "$dor_ready_keys" ]] && dor_ready_flag=" --dor-ready=$dor_ready_keys"
      fi

      cat <<EOF
Run /sweep:work-items ${delegate_args[*]}$dor_ready_flag
$directive_block
After /sweep:work-items generates its run dir (you'll see "Artifacts written to <PATH>"), run:
  bash <PATH>/let-it-rip.sh

Then report the <PATH> as the last line of your output, prefixed with DELEGATE_RUN_DIR=.
EOF
      ;;
  esac
}

# Dispatch one (delegate × tranche) combination.
# Takes ticket_keys: per-item directories and update_status are keyed on
# ticket_key. delegate_args (e.g. #<iid>) are resolved inside build_prompt.
dispatch_group() {
  local delegate=$1
  local tranche=$2
  shift 2
  local ticket_keys=("$@")

  local group_id="${delegate//:/-}-tranche-$tranche"
  local log_file="$RUN_DIR/$group_id.log"
  local prompt
  prompt=$(build_prompt "$delegate" "$tranche" "${ticket_keys[@]}")

  if (( DRY_RUN )); then
    echo "===== $group_id ====="
    echo "$prompt"
    echo "====="
    return 0
  fi

  log "starting $group_id (${#ticket_keys[@]} items: ${ticket_keys[*]})"
  for k in "${ticket_keys[@]}"; do update_status "$k" running; done

  # Run claude -p with the assembled prompt
  local exit_code=0
  echo "$prompt" | claude -p > "$log_file" 2>&1 || exit_code=$?

  # Extract DELEGATE_RUN_DIR= line from output
  local sub_dir
  sub_dir=$(grep -oE 'DELEGATE_RUN_DIR=.*' "$log_file" | tail -1 | cut -d= -f2- || true)

  if (( exit_code == 0 )); then
    log "done $group_id"
    for k in "${ticket_keys[@]}"; do update_status "$k" done "$sub_dir"; done
  else
    log "FAILED $group_id (exit $exit_code) — see $log_file"
    for k in "${ticket_keys[@]}"; do update_status "$k" failed "$sub_dir"; done
  fi
}

# Main loop: walk tranches sequentially
TRANCHE_LEVELS=$(jq -r '.tranches[].level' "$MANIFEST" | sort -n)

for level in $TRANCHE_LEVELS; do
  log "===== Tranche $level ====="
  pids=()

  # When CONVERGE=true, fold sweep:address-prs + sweep:review-prs items into a
  # single virtual delegate (`director`) so the runner spawns one /director
  # session that owns the review→address loop. sweep:work-items still
  # dispatches separately.
  if [[ "$CONVERGE" == "true" ]]; then
    delegates=(director sweep:work-items)
  else
    delegates=(sweep:address-prs sweep:review-prs sweep:work-items)
  fi

  for delegate in "${delegates[@]}"; do
    # Get ticket_keys for this (delegate, tranche). We pass keys (not delegate_args)
    # because per-item directories and update_status are keyed on ticket_key;
    # build_prompt resolves the actual delegate_args from the manifest.
    # while-read append instead of mapfile: mapfile is bash 4+ and this
    # template targets macOS default /bin/bash 3.2 (see pids note below).
    ticket_keys=()
    if [[ "$delegate" == "director" ]]; then
      while IFS= read -r _key; do
        [[ -n "$_key" ]] && ticket_keys+=("$_key")
      done < <(
        jq -r --argjson lvl "$level" \
          '.active[]
             | select(.tranche == $lvl)
             | select(.delegate_skill == "sweep:address-prs" or .delegate_skill == "sweep:review-prs")
             | .ticket_key' \
          "$MANIFEST"
      )
    else
      while IFS= read -r _key; do
        [[ -n "$_key" ]] && ticket_keys+=("$_key")
      done < <(
        jq -r --argjson lvl "$level" --arg del "$delegate" \
          '.active[] | select(.tranche == $lvl) | select(.delegate_skill == $del) | .ticket_key' \
          "$MANIFEST"
      )
    fi

    if (( ${#ticket_keys[@]} > 0 )); then
      dispatch_group "$delegate" "$level" "${ticket_keys[@]}" &
      pids+=($!)
    fi
  done

  # Wait for all delegates in this tranche.
  # Note `${pids[@]:-}` — bash 3.2 (macOS default) treats `${arr[@]}` on an
  # empty declared array as unbound under `set -u`, which would crash this
  # loop on tranches where no delegate had work.
  for pid in "${pids[@]:-}"; do
    [[ -z "$pid" ]] && continue
    wait "$pid" || log "WARN: pid $pid in tranche $level returned non-zero"
  done

  # Dry-run never produces `state: done`, so skip the "any-success" gate
  # and let the preview walk every tranche.
  if (( DRY_RUN )); then
    continue
  fi

  # Decide whether to proceed to next tranche
  any_done=0
  while IFS= read -r k; do
    if grep -q '^state: done' "$RUN_DIR/$k/status.md" 2>/dev/null; then
      any_done=1
      break
    fi
  done < <(jq -r --argjson lvl "$level" '.active[] | select(.tranche == $lvl) | .ticket_key' "$MANIFEST")

  if (( any_done )); then
    log "Tranche $level: at least one success, proceeding"
  else
    log "Tranche $level: NO successes — halting before subsequent tranches"
    break
  fi
done

log "Dispatch complete. See per-item status.md files for results."
