#!/bin/bash
# Sweep Runner — parallel claude -p sessions for PR processing
# Generated by /sweep-{{MODE}}-prs on {{TIMESTAMP}}
# Usage: bash {{RUN_DIR}}/let-it-rip.sh
#
# Template: ~/.claude/skill-references/parallel-claude-runner-template.sh
# Skills fill {{PLACEHOLDERS}} at generation time.

set -e

# --- Config (filled by skill) ---
RUN_DIR="{{RUN_DIR}}"           # absolute path
CONCURRENCY={{CONCURRENCY}}
PRS=({{PRS}})                   # space-separated PR numbers
MODE="{{MODE}}"                 # "review" or "address"
MODE_LABEL="{{MODE_LABEL}}"     # "Review" or "Address" (pre-capitalized for bash 3.x)
{{#BRANCHES}}
# Branch mapping (address mode only — function for bash 3.x compat on macOS)
branch_for() {
    case "$1" in
{{BRANCH_CASES}}
    esac
}
# Worktree path mapping — returns existing worktree or new path under RUN_DIR
worktree_for() {
    case "$1" in
{{WORKTREE_CASES}}
    esac
}
# PRs that need new worktrees (empty if all reused)
NEW_WORKTREE_PRS=({{NEW_WORKTREE_PRS}})
PROJECT_ROOT="{{PROJECT_ROOT}}"
{{/BRANCHES}}

# --- Worktree setup (address mode only) ---
{{#WORKTREES}}
setup_worktrees() {
    if [ ${#NEW_WORKTREE_PRS[@]} -eq 0 ]; then
        echo "All worktrees reused from existing checkouts."
        return
    fi
    mkdir -p "$RUN_DIR/worktrees"
    for pr_num in "${NEW_WORKTREE_PRS[@]}"; do
        local branch
        branch=$(branch_for "$pr_num")
        local wt
        wt=$(worktree_for "$pr_num")
        if [ ! -d "$wt" ]; then
            git -C "$PROJECT_ROOT" worktree add "$wt" "$branch" || {
                echo "WARNING: Failed to create worktree for PR $pr_num, skipping"
                continue
            }
        else
            git -C "$wt" pull --ff-only origin "$branch" 2>/dev/null || true
        fi
    done
}

cleanup_worktrees() {
    # Only clean up worktrees we created, not pre-existing ones
    for pr_num in "${NEW_WORKTREE_PRS[@]}"; do
        local wt
        wt=$(worktree_for "$pr_num")
        git -C "$PROJECT_ROOT" worktree remove "$wt" --force 2>/dev/null || true
    done
}

setup_worktrees
trap 'cleanup_worktrees' EXIT
{{/WORKTREES}}

# --- Header ---
echo ====================================================
echo "Sweep ${MODE_LABEL} Runner"
echo ====================================================
echo "Run directory: $RUN_DIR"
echo "PRs:           ${PRS[*]}"
echo "Concurrency:   $CONCURRENCY"
echo "Started at:    $(date)"
echo ====================================================
echo ""
echo "Watch progress in another terminal:"
echo "  while clear; do for f in $RUN_DIR/pr-*/status.md; do echo \"--- \$f\"; cat \"\$f\"; echo; done; sleep 5; done"
echo ""

OVERALL_START=$(date +%s)

# --- Per-PR function ---
process_pr() {
    local pr_num=$1
    local pr_dir="${RUN_DIR}/pr-${pr_num}"
    local log_file="${pr_dir}/output.log"
    local status_file="${pr_dir}/status.md"
    local start_time=$(date +%s)
    local ts=$(date +%H:%M:%S)

    # Pre-flight: skip if rate-limited
    if [ -f "${RUN_DIR}/.rate-limited" ]; then
        printf '# PR #%s\nmilestone: skipped\nreason: rate-limited\n' "$pr_num" > "$status_file"
        echo "[$ts] PR #${pr_num}: SKIPPED (rate-limited)"
        return
    fi

    # Pre-flight: skip if status.md shows terminal state (no API call needed)
    if [ -f "$status_file" ]; then
        local cached_state
        cached_state=$(grep '^pr_state:' "$status_file" 2>/dev/null | awk '{print $2}')
        if [ "$cached_state" = "MERGED" ] || [ "$cached_state" = "CLOSED" ]; then
            echo "[$ts] PR #${pr_num}: SKIPPED ($cached_state, from status.md)"
            return
        fi
    fi

    # Pre-flight: skip merged/closed PRs (API fallback for first run or missing status.md)
    local state
    state=$(gh pr view "$pr_num" --json state -q '.state' 2>/dev/null || echo "UNKNOWN")
    if [ "$state" != "OPEN" ]; then
        printf '# PR #%s\nmilestone: skipped\nreason: %s\npr_state: %s\n' "$pr_num" "$state" "$state" > "$status_file"
        echo "[$ts] PR #${pr_num}: SKIPPED ($state)"
        return
    fi

    echo "[$ts] PR #${pr_num}: launching claude -p session..."
    printf '# PR #%s Status\nmilestone: launching\nstarted_at: %s\n' \
        "$pr_num" "$(date -Iseconds)" > "$status_file"

    # Resolve stream monitor path (works from any CWD via HOME)
    local monitor="${HOME}/.claude/skill-references/stream-monitor.sh"

    # Launch with stream monitoring if monitor exists, otherwise fall back to plain pipe
    if [ -x "$monitor" ]; then
        if cat "${pr_dir}/prompt.txt" \
            | sh -c "echo \$\$ > ${pr_dir}/session.pid; exec claude -p --verbose --output-format stream-json" \
            | "$monitor" "$pr_dir" \
            | tee "$pr_dir/raw.jsonl" > "$log_file"; then
            local exit_status="success"
        else
            local exit_status="error"
            printf '# PR #%s Status\nmilestone: errored\nerror: claude session exited non-zero\n' \
                "$pr_num" > "$status_file"
        fi
    else
        if cat "${pr_dir}/prompt.txt" | claude -p 2>&1 | tee "$log_file"; then
            local exit_status="success"
        else
            local exit_status="error"
            printf '# PR #%s Status\nmilestone: errored\nerror: claude session exited non-zero\n' \
                "$pr_num" > "$status_file"
        fi
    fi

    # Rate limit detection
    if grep -q "hit your limit" "$log_file" 2>/dev/null; then
        printf '# PR #%s Status\nmilestone: rate-limited\n' "$pr_num" > "$status_file"
        touch "${RUN_DIR}/.rate-limited"
    fi

    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    local end_ts=$(date +%H:%M:%S)

    if [ "$exit_status" = "success" ]; then
        echo "[$end_ts] PR #${pr_num}: DONE (${duration}s)"
    else
        echo "[$end_ts] PR #${pr_num}: ERRORED (${duration}s)"
    fi
}

export -f process_pr
export RUN_DIR

# --- Launch ---
printf '%s\n' "${PRS[@]}" | xargs -P "$CONCURRENCY" -I {} bash -c 'process_pr "$@"' _ {}

# --- Summary ---
OVERALL_END=$(date +%s)
OVERALL_DURATION=$((OVERALL_END - OVERALL_START))

echo ""
echo ====================================================
echo "Sweep ${MODE_LABEL} Complete"
echo ====================================================
echo "Duration:    ${OVERALL_DURATION}s"
echo "Results in:  ${RUN_DIR}/"
echo ""

if [ -f "${RUN_DIR}/.rate-limited" ]; then
    echo "WARNING: At least one session hit rate limits."
    echo "Check logs and retry after limit resets."
    echo ""
fi

echo "View results:  ls ${RUN_DIR}/pr-*/result.md"
echo "Ask Claude:    Check progress on ${RUN_DIR}"
