#!/bin/bash
# Sweep Runner — parallel claude -p sessions for PR processing
# Generated by /sweep:{{MODE}}-prs on {{TIMESTAMP}}
# Usage: bash {{RUN_DIR}}/let-it-rip.sh
#
# Assembled by: fill-template.sh <this-template> <run-dir> > let-it-rip.sh
# Skills write metadata.json + data files to <run-dir>, then call fill-template.sh.

set -e

# --- Config (filled by fill-template.sh from metadata.json) ---
RUN_DIR="{{RUN_DIR}}"           # absolute path
CONCURRENCY={{CONCURRENCY}}
INACTIVITY_TIMEOUT_SEC=${INACTIVITY_TIMEOUT:-600}
MAX_ATTEMPTS=2
ITEMS=({{ITEMS}})               # space-separated entity numbers (PR or issue)
MODE="{{MODE}}"                 # "review" or "address"
MODE_LABEL="{{MODE_LABEL}}"     # "Review" or "Address" (pre-capitalized for bash 3.x)
MODEL="${MODEL:-{{MODEL}}}"     # claude model — runtime env override supported
ENTITY_PREFIX="{{ENTITY_PREFIX}}"     # "pr" or "issue" — controls directory naming
ENTITY_LABEL="{{ENTITY_LABEL}}"       # "PR" or "Issue" — controls log labels
STATE_FIELD="{{STATE_FIELD}}"         # "pr_state" or "issue_state" — status.md field name
STATE_CHECK_CMD="{{STATE_CHECK_CMD}}" # "gh pr view" / "glab mr view" or "gh issue view" / "glab issue view" — word-split intentionally; must be "<tool> <subcommand>" only, no embedded flags
TERMINAL_STATES="{{TERMINAL_STATES}}" # space-separated single-word state tokens (word-boundary matched by is_terminal_state)
{{#BRANCHES}}
# Branch mapping (address mode only — function for bash 3.x compat on macOS)
branch_for() {
    case "$1" in
{@branch-cases.txt}
    esac
}
# Worktree path mapping — returns existing worktree or new path under RUN_DIR
worktree_for() {
    case "$1" in
{@worktree-cases.txt}
    esac
}
# PRs that need new worktrees (empty if all reused)
NEW_WORKTREE_ITEMS=({@new-worktree-items.txt})
PROJECT_ROOT="{{PROJECT_ROOT}}"
{{/BRANCHES}}

# --- Worktree setup (address mode only) ---
{{#WORKTREES}}
setup_worktrees() {
    if [ ${#NEW_WORKTREE_ITEMS[@]} -eq 0 ]; then
        echo "All worktrees reused from existing checkouts."
        return
    fi
    mkdir -p "$RUN_DIR/worktrees"
    for item_num in "${NEW_WORKTREE_ITEMS[@]}"; do
        local branch
        branch=$(branch_for "$item_num")
        local wt
        wt=$(worktree_for "$item_num")
        if [ ! -d "$wt" ]; then
            git -C "$PROJECT_ROOT" worktree add "$wt" "$branch" || {
                echo "WARNING: Failed to create worktree for ${ENTITY_LABEL} $item_num, skipping"
                continue
            }
        else
            git -C "$wt" pull --ff-only origin "$branch" 2>/dev/null || true
        fi
    done
}

cleanup_worktrees() {
    # Only clean up worktrees we created, not pre-existing ones
    for item_num in "${NEW_WORKTREE_ITEMS[@]}"; do
        local wt
        wt=$(worktree_for "$item_num")
        git -C "$PROJECT_ROOT" worktree remove "$wt" --force 2>/dev/null || true
    done
}

setup_worktrees
trap 'cleanup_worktrees' EXIT
{{/WORKTREES}}

# --- Header ---
echo ====================================================
echo "Sweep ${MODE_LABEL} Runner"
echo ====================================================
echo "Run directory: $RUN_DIR"
echo "${ENTITY_LABEL}s:         ${ITEMS[*]}"
echo "Concurrency:   $CONCURRENCY"
echo "Started at:    $(date)"
echo ====================================================
echo ""
echo "Watch progress in another terminal:"
echo "  while clear; do for f in $RUN_DIR/${ENTITY_PREFIX}-*/status.md; do echo \"--- \$f\"; cat \"\$f\"; echo; done; sleep 5; done"
echo ""

# Clear stale rate-limit sentinel from prior runs
rm -f "${RUN_DIR}/.rate-limited"

OVERALL_START=$(date +%s)

# --- Manifest updates (incremental additions/closures) ---
if [ -f "${RUN_DIR}/manifest-updates.json" ]; then
    while IFS= read -r line; do
        action=$(printf '%s' "$line" | jq -r '.action // empty' 2>/dev/null) || continue
        item_id=$(printf '%s' "$line" | jq -r '.id // .item.id // empty' 2>/dev/null) || continue
        if [ "$action" = "add" ] && [ -n "$item_id" ]; then
            # Dedup: skip if already in ITEMS array
            local already_present=false
            for existing in "${ITEMS[@]}"; do
                if [ "$existing" = "$item_id" ]; then
                    already_present=true
                    break
                fi
            done
            if [ "$already_present" = false ] && [ -f "${RUN_DIR}/${ENTITY_PREFIX}-${item_id}/prompt.txt" ]; then
                ITEMS+=("$item_id")
            fi
        elif [ "$action" = "close" ] && [ -n "$item_id" ]; then
            close_reason=$(printf '%s' "$line" | jq -r '.reason // empty' 2>/dev/null)
            mkdir -p "${RUN_DIR}/${ENTITY_PREFIX}-${item_id}"
            printf '# %s #%s\nmilestone: closed\nreason: %s\n%s: CLOSED\n' \
                "$ENTITY_LABEL" "$item_id" "${close_reason:-director-closed}" "$STATE_FIELD" \
                > "${RUN_DIR}/${ENTITY_PREFIX}-${item_id}/status.md"
        fi
    done < "${RUN_DIR}/manifest-updates.json"
fi

# --- State writer ---
write_state() {
    local item_num=$1 state=$2
    local item_dir="${RUN_DIR}/${ENTITY_PREFIX}-${item_num}"
    local now
    now=$(date -Iseconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S%z)
    {
        printf 'state: %s\n' "$state"
        printf 'updated_at: %s\n' "$now"
        shift 2
        while [ $# -gt 0 ]; do
            printf '%s\n' "$1"
            shift
        done
    } > "${item_dir}/state.md"
}

# --- Terminal state check ---
is_terminal_state() {
    local state=$1
    [ -z "$state" ] && return 1
    case " $TERMINAL_STATES " in
        *" $state "*) return 0 ;;
        *) return 1 ;;
    esac
}

# --- Per-item function ---
process_item() {
    local item_num=$1
    local item_dir="${RUN_DIR}/${ENTITY_PREFIX}-${item_num}"
    local log_file="${item_dir}/output.log"
    local status_file="${item_dir}/status.md"
    local start_time=$(date +%s)
    local ts=$(date +%H:%M:%S)

    # Pre-flight: skip only on terminal entity states — not on "done".
    # "done" means the *previous* cycle completed, not that there's nothing to do.
    # The session's watermark logic handles rerun detection (compares HEAD SHA +
    # comment IDs against current state). The runner only skips truly terminal cases.
    if [ -f "$status_file" ]; then
        local cached_state
        cached_state=$(grep "^${STATE_FIELD}:" "$status_file" 2>/dev/null | awk '{print $2}')
        if is_terminal_state "$cached_state"; then
            echo "[$ts] ${ENTITY_LABEL} #${item_num}: SKIPPED ($cached_state, from status.md)"
            return
        fi
    fi

    # Pre-flight: skip if rate-limited (after terminal check so completed sessions aren't regressed)
    if [ -f "${RUN_DIR}/.rate-limited" ]; then
        printf '# %s #%s\nmilestone: skipped\nreason: rate-limited\n' "$ENTITY_LABEL" "$item_num" > "$status_file"
        echo "[$ts] ${ENTITY_LABEL} #${item_num}: SKIPPED (rate-limited)"
        return
    fi

    # Pre-flight: skip terminal entities (API fallback for first run or missing status.md)
    local state
    state=$($STATE_CHECK_CMD "$item_num" --json state -q '.state' 2>/dev/null || echo "UNKNOWN")
    if [ "$state" = "UNKNOWN" ]; then
        printf '# %s #%s\nmilestone: api-error\nreason: state-check-failed\n%s: UNKNOWN\n' "$ENTITY_LABEL" "$item_num" "$STATE_FIELD" > "$status_file"
        echo "[$ts] ${ENTITY_LABEL} #${item_num}: SKIPPED (api-error)"
        return
    fi
    if is_terminal_state "$state"; then
        printf '# %s #%s\nmilestone: skipped\nreason: %s\n%s: %s\n' "$ENTITY_LABEL" "$item_num" "$state" "$STATE_FIELD" "$state" > "$status_file"
        echo "[$ts] ${ENTITY_LABEL} #${item_num}: SKIPPED ($state)"
        return
    fi

    echo "[$ts] ${ENTITY_LABEL} #${item_num}: launching claude -p session..."
    printf '# %s #%s Status\nmilestone: launching\nstarted_at: %s\n' \
        "$ENTITY_LABEL" "$item_num" "$(date -Iseconds)" > "$status_file"

    # Archive previous cycle's raw.jsonl (raw-1.jsonl, raw-2.jsonl, ...)
    if [ -f "$item_dir/raw.jsonl" ]; then
        local archive_num=1
        while [ -f "${item_dir}/raw-${archive_num}.jsonl" ]; do
            archive_num=$((archive_num + 1))
        done
        mv "$item_dir/raw.jsonl" "${item_dir}/raw-${archive_num}.jsonl"
    fi

    # Determine launch mode: resume or fresh start
    local use_resume=false
    local resume_session_id=""
    local resume_flag=""
    local cycle=1
    local prev_cost_usd=0

    if [ -f "$item_dir/session.reset" ]; then
        rm -f "$item_dir/session.state" "$item_dir/session.reset"
    elif [ -f "$item_dir/session.state" ]; then
        local state_mtime
        state_mtime=$(stat -f%m "$item_dir/session.state" 2>/dev/null \
            || stat -c%Y "$item_dir/session.state" 2>/dev/null || echo 0)
        local state_age=$(( $(date +%s) - state_mtime ))
        if [ "$state_age" -lt 21600 ]; then
            resume_session_id=$(grep '^session_id=' "$item_dir/session.state" | cut -d= -f2)
            prev_cost_usd=$(grep '^prev_cost_usd=' "$item_dir/session.state" | cut -d= -f2 || echo 0)
            cycle=$(grep '^cycle=' "$item_dir/session.state" | cut -d= -f2 || echo 1)
            if [ -n "$resume_session_id" ]; then
                use_resume=true
                resume_flag="--resume $resume_session_id"
            fi
        else
            rm -f "$item_dir/session.state"
        fi
    fi

    # Append cycle boundary to live.md so director can distinguish cycles
    printf '\n### Cycle %d — %s ###\n' "$cycle" "$(date -Iseconds)" >> "$item_dir/live.md"

    # Resolve stream monitor path (works from any CWD via HOME)
    local monitor="${HOME}/.claude/skill-references/stream-monitor.sh"

    local attempt=0
    while [ "$attempt" -lt "$MAX_ATTEMPTS" ]; do
        attempt=$((attempt + 1))
        local exit_status=""
        local attempt_start=$(date +%s)

        write_state "$item_num" "running" "attempt: $attempt" "max_attempts: $MAX_ATTEMPTS" "started_at: $(date -Iseconds)"

        # Add attempt boundary marker for raw.jsonl (append-only across retries)
        if [ "$attempt" -gt 1 ]; then
            printf '### attempt %d ###\n' "$attempt" >> "$item_dir/raw.jsonl"
        fi

        # Launch with stream monitoring if monitor exists, otherwise fall back to plain pipe
        if [ -x "$monitor" ]; then
            {
                if [ "$use_resume" = true ]; then
                    printf 'Cycle %d. Check directives.md for new directives since your last run. Continue.' "$cycle"
                else
                    cat "${item_dir}/prompt.txt"
                fi
            } \
                | sh -c "echo \$\$ > ${item_dir}/session.pid; exec claude -p --model $MODEL --verbose --output-format stream-json $resume_flag" \
                | "$monitor" "$item_dir" \
                | tee -a "$item_dir/raw.jsonl" >> "$log_file" &
            local pipe_pid=$!

            # Inactivity monitoring loop
            while kill -0 "$pipe_pid" 2>/dev/null; do
                sleep 30
                local now_epoch=$(date +%s)
                local live_file="${item_dir}/live.md"
                if [ -f "$live_file" ]; then
                    local live_mtime
                    live_mtime=$(stat -c %Y "$live_file" 2>/dev/null || stat -f %m "$live_file" 2>/dev/null || echo "$now_epoch")
                    local idle_seconds=$((now_epoch - live_mtime))
                    if [ "$idle_seconds" -gt "$INACTIVITY_TIMEOUT_SEC" ]; then
                        echo "[$(date +%H:%M:%S)] ${ENTITY_LABEL} #${item_num}: inactivity timeout (${idle_seconds}s idle, attempt ${attempt}/${MAX_ATTEMPTS})"
                        # Kill the claude session
                        if [ -f "${item_dir}/session.pid" ]; then
                            kill "$(cat "${item_dir}/session.pid")" 2>/dev/null || true
                        fi
                        kill "$pipe_pid" 2>/dev/null || true
                        wait "$pipe_pid" 2>/dev/null || true
                        exit_status="timeout"
                        break
                    fi
                fi
            done

            # If the loop ended without timeout, collect exit code
            if [ -z "$exit_status" ]; then
                if wait "$pipe_pid"; then
                    exit_status="success"
                else
                    exit_status="error"
                fi
            fi
        else
            local fallback_timeout=$((INACTIVITY_TIMEOUT_SEC * 2))
            if timeout "$fallback_timeout" sh -c "cat \"\$1\" | claude -p --model $MODEL 2>&1 | tee -a \"\$2\"" _ "${item_dir}/prompt.txt" "$log_file"; then
                exit_status="success"
            else
                local fallback_rc=$?
                if [ "$fallback_rc" -eq 124 ]; then
                    exit_status="timeout"
                else
                    exit_status="error"
                fi
            fi
        fi

        local end_time=$(date +%s)
        local duration=$((end_time - attempt_start))
        local end_ts=$(date +%H:%M:%S)

        # Handle exit status — success takes priority over transient rate limits
        if [ "$exit_status" = "success" ]; then
            echo "[$end_ts] ${ENTITY_LABEL} #${item_num}: DONE (${duration}s, attempt ${attempt}/${MAX_ATTEMPTS})"

            # Compute context window usage from the latest assistant message's usage block.
            # cache_read + cache_creation + input_tokens = total tokens the model processed this turn,
            # which equals the conversation context size at that point.
            local context_used=0 context_pct=0 context_window=200000
            local last_usage
            last_usage=$(jq -c 'select(.type == "assistant") | .message.usage // empty' "$item_dir/raw.jsonl" 2>/dev/null | tail -1)
            if [ -n "$last_usage" ]; then
                local in_tok cc_tok cr_tok
                in_tok=$(printf '%s' "$last_usage" | jq -r '.input_tokens // 0')
                cc_tok=$(printf '%s' "$last_usage" | jq -r '.cache_creation_input_tokens // 0')
                cr_tok=$(printf '%s' "$last_usage" | jq -r '.cache_read_input_tokens // 0')
                context_used=$((in_tok + cc_tok + cr_tok))
            fi
            case "$MODEL" in
                *\[1m\]*) context_window=1000000 ;;
            esac
            if [ "$context_used" -gt 0 ]; then
                context_pct=$((context_used * 100 / context_window))
            fi

            write_state "$item_num" "completed" \
                "attempt: $attempt" \
                "max_attempts: $MAX_ATTEMPTS" \
                "duration_seconds: $duration" \
                "context_used_tokens: $context_used" \
                "context_window: $context_window" \
                "context_pct: $context_pct"

            # Persist session state for next cycle (resume support)
            local result_line
            result_line=$(jq -c 'select(.type == "result" and .subtype == "success")' "$item_dir/raw.jsonl" 2>/dev/null | tail -1)
            if [ -n "$result_line" ]; then
                local new_session_id new_cost_usd
                new_session_id=$(printf '%s' "$result_line" | jq -r '.session_id // empty')
                new_cost_usd=$(printf '%s' "$result_line" | jq -r '.total_cost_usd // 0')
                if [ -n "$new_session_id" ]; then
                    printf 'session_id=%s\nprev_cost_usd=%s\ncycle=%d\n' \
                        "$new_session_id" "$new_cost_usd" "$((cycle + 1))" > "$item_dir/session.state"
                fi
            fi
            return
        fi

        # Rate limit detection (only on failure — transient limits during successful sessions are harmless)
        if grep -q "hit your limit" "$log_file" 2>/dev/null; then
            exit_status="rate-limited"
            printf '# %s #%s Status\nmilestone: rate-limited\n' "$ENTITY_LABEL" "$item_num" > "$status_file"
            touch "${RUN_DIR}/.rate-limited"
            write_state "$item_num" "rate-limited" "attempt: $attempt" "max_attempts: $MAX_ATTEMPTS"
            break
        fi

        # Resume fallback: if session not found, switch to fresh start (don't count as an attempt)
        if [ "$use_resume" = true ] && grep -q "No conversation found" "$item_dir/raw.jsonl" 2>/dev/null; then
            echo "[$end_ts] ${ENTITY_LABEL} #${item_num}: resume session expired — falling back to fresh start"
            rm -f "$item_dir/session.state"
            use_resume=false
            resume_session_id=""
            resume_flag=""
            cycle=1
            attempt=$((attempt - 1))
            continue
        fi

        # Failure — retry or escalate
        if [ "$attempt" -lt "$MAX_ATTEMPTS" ]; then
            echo "[$end_ts] ${ENTITY_LABEL} #${item_num}: FAILED (${duration}s, attempt ${attempt}/${MAX_ATTEMPTS}) — retrying in 5s..."
            write_state "$item_num" "retrying" "attempt: $attempt" "max_attempts: $MAX_ATTEMPTS" "previous_exit: $exit_status"
            sleep 5
            continue
        fi

        # Final attempt exhausted
        echo "[$end_ts] ${ENTITY_LABEL} #${item_num}: ERRORED (${duration}s, attempt ${attempt}/${MAX_ATTEMPTS})"
        printf '# %s #%s Status\nmilestone: errored\nerror: %s after %d attempts\n' \
            "$ENTITY_LABEL" "$item_num" "$exit_status" "$MAX_ATTEMPTS" > "$status_file"
        write_state "$item_num" "errored" "attempt: $attempt" "max_attempts: $MAX_ATTEMPTS" "exit_reason: $exit_status" "escalation: needs-director"
        return
    done
}

export -f process_item write_state is_terminal_state
export RUN_DIR INACTIVITY_TIMEOUT_SEC MAX_ATTEMPTS MODEL MODE_LABEL ENTITY_PREFIX ENTITY_LABEL STATE_FIELD STATE_CHECK_CMD TERMINAL_STATES

# --- Launch ---
printf '%s\n' "${ITEMS[@]}" | xargs -P "$CONCURRENCY" -I {} bash -c 'process_item "$@"' _ {}

# --- Summary ---
OVERALL_END=$(date +%s)
OVERALL_DURATION=$((OVERALL_END - OVERALL_START))

echo ""
echo ====================================================
echo "Sweep ${MODE_LABEL} Complete"
echo ====================================================
echo "Duration:    ${OVERALL_DURATION}s"
echo "Results in:  ${RUN_DIR}/"
echo ""

if [ -f "${RUN_DIR}/.rate-limited" ]; then
    echo "WARNING: At least one session hit rate limits."
    echo "Check logs and retry after limit resets."
    echo ""
fi

echo "View results:  ls ${RUN_DIR}/${ENTITY_PREFIX}-*/results.md"
echo "Ask Claude:    Check progress on ${RUN_DIR}"
