#!/bin/bash
# Work-Items Sweep Runner — parallel claude -p sessions for issue processing
# Generated by /sweep:work-items on {{TIMESTAMP}}
# Usage: bash {{RUN_DIR}}/let-it-rip.sh
#
# Assembled by: fill-template.sh <this-template> <run-dir> > let-it-rip.sh
# Skills write metadata.json + data files to <run-dir>, then call fill-template.sh.
#
# Adapts the generic parallel-claude-runner-template.sh to issue semantics:
#   - issue-<N>/ dirs (vs pr-<N>/)
#   - `gh issue view` (vs `gh pr view`)
#   - issue_state: + only CLOSED is terminal (no MERGED for issues)
# Adds work-items-specific worktree setup for implementer sessions:
#   - For each issue in IMPLEMENT_ISSUES, create a git worktree under
#     <RUN_DIR>/worktrees/issue-<N>/ on a fresh sweep/<N>-impl branch from
#     the issue's BASE_BRANCH (read from <RUN_DIR>/issue-<N>/metadata.json).
#   - The implementer prompt cd's into its worktree before launching claude -p,
#     and renames the branch to sweep/<N>-<slug> as part of its git workflow.
#   - Worktrees are preserved across runs (per work-items SKILL); operator
#     removes manually with `git worktree remove`.

set -e

# --- Config (filled by fill-template.sh from metadata.json) ---
RUN_DIR="{{RUN_DIR}}"
CONCURRENCY={{CONCURRENCY}}
INACTIVITY_TIMEOUT_SEC=${INACTIVITY_TIMEOUT:-600}
MAX_ATTEMPTS=2
ISSUES=({{PRS}})                              # all eligible issue numbers
IMPLEMENT_ISSUES=({{IMPLEMENT_ISSUES}})       # subset that need worktrees + git workflow
MODE="{{MODE}}"                               # clarify | confirm | implement | mixed
MODE_LABEL="{{MODE_LABEL}}"
MODEL="${MODEL:-{{MODEL}}}"
PROJECT_ROOT="{{PROJECT_ROOT}}"

# Default PROJECT_ROOT to the git toplevel of the runner's CWD if unset.
if [ -z "$PROJECT_ROOT" ]; then
    PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
fi

WORKTREE_BASE="${RUN_DIR}/worktrees"

# --- Worktree setup (only runs if IMPLEMENT_ISSUES non-empty) ---
worktree_for() {
    echo "${WORKTREE_BASE}/issue-$1"
}

setup_worktree_for() {
    local n=$1
    local meta="${RUN_DIR}/issue-${n}/metadata.json"
    local base_branch
    base_branch=$(jq -r '.BASE_BRANCH // "main"' "$meta" 2>/dev/null || echo main)
    [ -z "$base_branch" ] || [ "$base_branch" = "null" ] && base_branch="main"

    local wt
    wt=$(worktree_for "$n")
    local wt_branch="sweep/${n}-impl"

    # Skip if worktree already mounted at the expected path
    if git -C "$PROJECT_ROOT" worktree list --porcelain 2>/dev/null | grep -qE "^worktree ${wt}\$"; then
        echo "  worktree #${n} reused at ${wt}"
        return 0
    fi

    # Fetch non-default base branches (for stacked dependencies)
    if [ "$base_branch" != "main" ] && [ "$base_branch" != "master" ]; then
        git -C "$PROJECT_ROOT" fetch origin "$base_branch" 2>/dev/null || true
    fi

    # Create or reuse the placeholder branch (implementer renames in Step 14)
    if git -C "$PROJECT_ROOT" show-ref --verify --quiet "refs/heads/${wt_branch}"; then
        echo "  worktree #${n} on existing branch ${wt_branch}"
        git -C "$PROJECT_ROOT" worktree add "$wt" "$wt_branch" 2>&1 | sed 's/^/    /' || {
            echo "  WARNING: failed to mount worktree for #${n} on existing branch"
            return 1
        }
    else
        echo "  worktree #${n} new branch ${wt_branch} from ${base_branch}"
        git -C "$PROJECT_ROOT" worktree add -b "$wt_branch" "$wt" "$base_branch" 2>&1 | sed 's/^/    /' || {
            echo "  WARNING: failed to create worktree for #${n}"
            return 1
        }
    fi
}

if [ ${#IMPLEMENT_ISSUES[@]} -gt 0 ]; then
    mkdir -p "$WORKTREE_BASE"
    echo "=== Setting up worktrees for ${#IMPLEMENT_ISSUES[@]} implementer(s) ==="
    for n in "${IMPLEMENT_ISSUES[@]}"; do
        setup_worktree_for "$n"
    done
    echo ""
fi

# --- Header ---
echo ====================================================
echo "Work-Items Sweep Runner — ${MODE_LABEL}"
echo ====================================================
echo "Run directory:      $RUN_DIR"
echo "Project root:       $PROJECT_ROOT"
echo "Issues:             ${ISSUES[*]}"
echo "Implementer issues: ${IMPLEMENT_ISSUES[*]:-(none)}"
echo "Concurrency:        $CONCURRENCY"
echo "Started at:         $(date)"
echo ====================================================
echo ""

rm -f "${RUN_DIR}/.rate-limited"
OVERALL_START=$(date +%s)

# --- State writer ---
write_state() {
    local n=$1 state=$2
    local issue_dir="${RUN_DIR}/issue-${n}"
    local now
    now=$(date -Iseconds 2>/dev/null || date +%Y-%m-%dT%H:%M:%S%z)
    {
        printf 'state: %s\n' "$state"
        printf 'updated_at: %s\n' "$now"
        shift 2
        while [ $# -gt 0 ]; do
            printf '%s\n' "$1"
            shift
        done
    } > "${issue_dir}/state.md"
}

# --- Membership helper for implement issues (string-based for subshell safety) ---
is_implementer() {
    [ -z "${IMPLEMENT_ISSUES_STR:-}" ] && return 1
    case " ${IMPLEMENT_ISSUES_STR} " in
        *" $1 "*) return 0 ;;
        *)        return 1 ;;
    esac
}

# --- Per-issue function ---
process_issue() {
    local n=$1
    local issue_dir="${RUN_DIR}/issue-${n}"
    local log_file="${issue_dir}/output.log"
    local status_file="${issue_dir}/status.md"
    local start_time=$(date +%s)
    local ts=$(date +%H:%M:%S)

    # Pre-flight 1: local status.md (free)
    if [ -f "$status_file" ]; then
        local cached_state
        cached_state=$(grep '^issue_state:' "$status_file" 2>/dev/null | awk '{print $2}')
        if [ "$cached_state" = "CLOSED" ]; then
            echo "[$ts] Issue #${n}: SKIPPED (CLOSED, from status.md)"
            return
        fi
        local pr_opened
        pr_opened=$(grep '^pr_opened:' "$status_file" 2>/dev/null | awk '{print $2}')
        if [ "$pr_opened" = "true" ]; then
            echo "[$ts] Issue #${n}: SKIPPED (PR already opened, from status.md)"
            return
        fi
    fi

    # Pre-flight 2: rate limit (after terminal so completed sessions aren't regressed)
    if [ -f "${RUN_DIR}/.rate-limited" ]; then
        printf '# Issue #%s\nmilestone: skipped\nreason: rate-limited\n' "$n" > "$status_file"
        echo "[$ts] Issue #${n}: SKIPPED (rate-limited)"
        return
    fi

    # Pre-flight 3: API state check (1 API call) — covers first-run + externally-changed issues
    local state
    state=$(gh issue view "$n" --json state -q '.state' 2>/dev/null || echo "UNKNOWN")
    if [ "$state" = "CLOSED" ]; then
        printf '# Issue #%s\nmilestone: skipped\nreason: %s\nissue_state: %s\n' "$n" "$state" "$state" > "$status_file"
        echo "[$ts] Issue #${n}: SKIPPED ($state)"
        return
    fi

    # Determine launch CWD: implementer → its worktree, else project root
    local launch_cwd="$PROJECT_ROOT"
    if is_implementer "$n"; then
        launch_cwd=$(worktree_for "$n")
        if [ ! -d "$launch_cwd" ]; then
            echo "[$ts] Issue #${n}: ERROR worktree missing: ${launch_cwd}"
            printf '# Issue #%s Status\nmilestone: errored\nerror: worktree missing at %s\n' \
                "$n" "$launch_cwd" > "$status_file"
            write_state "$n" "errored" "exit_reason: worktree-missing" "escalation: needs-director"
            return
        fi
    fi

    echo "[$ts] Issue #${n}: launching claude -p (cwd=${launch_cwd})..."
    printf '# Issue #%s Status\nmilestone: launching\nstarted_at: %s\ncwd: %s\n' \
        "$n" "$(date -Iseconds)" "$launch_cwd" > "$status_file"

    # Archive previous cycle's raw.jsonl
    if [ -f "$issue_dir/raw.jsonl" ]; then
        local archive_num=1
        while [ -f "${issue_dir}/raw-${archive_num}.jsonl" ]; do
            archive_num=$((archive_num + 1))
        done
        mv "$issue_dir/raw.jsonl" "${issue_dir}/raw-${archive_num}.jsonl"
    fi

    # Resume support
    local use_resume=false resume_flag="" cycle=1 prev_cost_usd=0
    if [ -f "$issue_dir/session.reset" ]; then
        rm -f "$issue_dir/session.state" "$issue_dir/session.reset"
    elif [ -f "$issue_dir/session.state" ]; then
        local state_mtime
        state_mtime=$(stat -f%m "$issue_dir/session.state" 2>/dev/null \
            || stat -c%Y "$issue_dir/session.state" 2>/dev/null || echo 0)
        local state_age=$(( $(date +%s) - state_mtime ))
        if [ "$state_age" -lt 21600 ]; then
            local resume_id
            resume_id=$(grep '^session_id=' "$issue_dir/session.state" | cut -d= -f2)
            cycle=$(grep '^cycle=' "$issue_dir/session.state" | cut -d= -f2 || echo 1)
            if [ -n "$resume_id" ]; then
                use_resume=true
                resume_flag="--resume $resume_id"
            fi
        else
            rm -f "$issue_dir/session.state"
        fi
    fi

    printf '\n### Cycle %d — %s ###\n' "$cycle" "$(date -Iseconds)" >> "$issue_dir/live.md"

    local monitor="${HOME}/.claude/skill-references/stream-monitor.sh"

    local attempt=0
    while [ "$attempt" -lt "$MAX_ATTEMPTS" ]; do
        attempt=$((attempt + 1))
        local exit_status=""
        local attempt_start=$(date +%s)

        write_state "$n" "running" \
            "attempt: $attempt" "max_attempts: $MAX_ATTEMPTS" \
            "started_at: $(date -Iseconds)" "cwd: $launch_cwd"

        if [ "$attempt" -gt 1 ]; then
            printf '### attempt %d ###\n' "$attempt" >> "$issue_dir/raw.jsonl"
        fi

        if [ -x "$monitor" ]; then
            {
                if [ "$use_resume" = true ]; then
                    printf 'Cycle %d. Check directives.md for new directives since your last run. Continue.' "$cycle"
                else
                    cat "${issue_dir}/prompt.txt"
                fi
            } \
                | sh -c "cd '$launch_cwd' && echo \$\$ > '${issue_dir}/session.pid' && exec claude -p --model $MODEL --verbose --output-format stream-json $resume_flag" \
                | "$monitor" "$issue_dir" \
                | tee -a "$issue_dir/raw.jsonl" >> "$log_file" &
            local pipe_pid=$!

            while kill -0 "$pipe_pid" 2>/dev/null; do
                sleep 30
                local now_epoch=$(date +%s)
                local live_file="${issue_dir}/live.md"
                if [ -f "$live_file" ]; then
                    local live_mtime
                    live_mtime=$(stat -c %Y "$live_file" 2>/dev/null || stat -f %m "$live_file" 2>/dev/null || echo "$now_epoch")
                    local idle_seconds=$((now_epoch - live_mtime))
                    if [ "$idle_seconds" -gt "$INACTIVITY_TIMEOUT_SEC" ]; then
                        echo "[$(date +%H:%M:%S)] Issue #${n}: inactivity timeout (${idle_seconds}s idle)"
                        if [ -f "${issue_dir}/session.pid" ]; then
                            kill "$(cat "${issue_dir}/session.pid")" 2>/dev/null || true
                        fi
                        kill "$pipe_pid" 2>/dev/null || true
                        wait "$pipe_pid" 2>/dev/null || true
                        exit_status="timeout"
                        break
                    fi
                fi
            done

            if [ -z "$exit_status" ]; then
                if wait "$pipe_pid"; then exit_status="success"; else exit_status="error"; fi
            fi
        else
            local fallback_timeout=$((INACTIVITY_TIMEOUT_SEC * 2))
            if timeout "$fallback_timeout" sh -c "cd '$launch_cwd' && cat \"\$1\" | claude -p --model $MODEL 2>&1 | tee -a \"\$2\"" _ "${issue_dir}/prompt.txt" "$log_file"; then
                exit_status="success"
            else
                local fallback_rc=$?
                if [ "$fallback_rc" -eq 124 ]; then exit_status="timeout"; else exit_status="error"; fi
            fi
        fi

        local end_time=$(date +%s)
        local duration=$((end_time - attempt_start))
        local end_ts=$(date +%H:%M:%S)

        if [ "$exit_status" = "success" ]; then
            echo "[$end_ts] Issue #${n}: DONE (${duration}s, attempt ${attempt}/${MAX_ATTEMPTS})"

            local context_used=0 context_pct=0 context_window=200000
            local last_usage
            last_usage=$(jq -c 'select(.type == "assistant") | .message.usage // empty' "$issue_dir/raw.jsonl" 2>/dev/null | tail -1)
            if [ -n "$last_usage" ]; then
                local in_tok cc_tok cr_tok
                in_tok=$(printf '%s' "$last_usage" | jq -r '.input_tokens // 0')
                cc_tok=$(printf '%s' "$last_usage" | jq -r '.cache_creation_input_tokens // 0')
                cr_tok=$(printf '%s' "$last_usage" | jq -r '.cache_read_input_tokens // 0')
                context_used=$((in_tok + cc_tok + cr_tok))
            fi
            case "$MODEL" in *\[1m\]*) context_window=1000000 ;; esac
            if [ "$context_used" -gt 0 ]; then
                context_pct=$((context_used * 100 / context_window))
            fi

            write_state "$n" "completed" \
                "attempt: $attempt" "max_attempts: $MAX_ATTEMPTS" \
                "duration_seconds: $duration" \
                "context_used_tokens: $context_used" \
                "context_window: $context_window" \
                "context_pct: $context_pct" \
                "cwd: $launch_cwd"

            local result_line
            result_line=$(jq -c 'select(.type == "result" and .subtype == "success")' "$issue_dir/raw.jsonl" 2>/dev/null | tail -1)
            if [ -n "$result_line" ]; then
                local new_session_id new_cost_usd
                new_session_id=$(printf '%s' "$result_line" | jq -r '.session_id // empty')
                new_cost_usd=$(printf '%s' "$result_line" | jq -r '.total_cost_usd // 0')
                if [ -n "$new_session_id" ]; then
                    printf 'session_id=%s\nprev_cost_usd=%s\ncycle=%d\n' \
                        "$new_session_id" "$new_cost_usd" "$((cycle + 1))" > "$issue_dir/session.state"
                fi
            fi
            return
        fi

        if grep -q "hit your limit" "$log_file" 2>/dev/null; then
            exit_status="rate-limited"
            printf '# Issue #%s Status\nmilestone: rate-limited\n' "$n" > "$status_file"
            touch "${RUN_DIR}/.rate-limited"
            write_state "$n" "rate-limited" "attempt: $attempt"
            break
        fi

        if [ "$use_resume" = true ] && grep -q "No conversation found" "$issue_dir/raw.jsonl" 2>/dev/null; then
            echo "[$end_ts] Issue #${n}: resume expired — falling back to fresh"
            rm -f "$issue_dir/session.state"
            use_resume=false; resume_flag=""; cycle=1
            attempt=$((attempt - 1))
            continue
        fi

        if [ "$attempt" -lt "$MAX_ATTEMPTS" ]; then
            echo "[$end_ts] Issue #${n}: FAILED (${duration}s, attempt ${attempt}/${MAX_ATTEMPTS}) — retrying in 5s..."
            write_state "$n" "retrying" "attempt: $attempt" "previous_exit: $exit_status"
            sleep 5
            continue
        fi

        echo "[$end_ts] Issue #${n}: ERRORED (${duration}s, all attempts failed)"
        printf '# Issue #%s Status\nmilestone: errored\nerror: %s after %d attempts\n' \
            "$n" "$exit_status" "$MAX_ATTEMPTS" > "$status_file"
        write_state "$n" "errored" "attempt: $attempt" "exit_reason: $exit_status" "escalation: needs-director"
        return
    done
}

export -f process_issue write_state is_implementer worktree_for
export RUN_DIR INACTIVITY_TIMEOUT_SEC MAX_ATTEMPTS MODEL MODE_LABEL PROJECT_ROOT WORKTREE_BASE
export IMPLEMENT_ISSUES_STR="${IMPLEMENT_ISSUES[*]}"

# --- Launch in parallel via xargs ---
printf '%s\n' "${ISSUES[@]}" | xargs -P "$CONCURRENCY" -I {} bash -c 'process_issue "$@"' _ {}

OVERALL_END=$(date +%s)
OVERALL_DURATION=$((OVERALL_END - OVERALL_START))

echo ""
echo ====================================================
echo "Work-Items Sweep Complete"
echo ====================================================
echo "Duration:    ${OVERALL_DURATION}s"
echo "Results in:  ${RUN_DIR}/"
echo ""

if [ -f "${RUN_DIR}/.rate-limited" ]; then
    echo "WARNING: At least one session hit rate limits. Retry after limit resets."
    echo ""
fi

if [ ${#IMPLEMENT_ISSUES[@]} -gt 0 ]; then
    echo "Worktrees preserved at: ${WORKTREE_BASE}/issue-<N>"
    echo "  Inspect:  ls ${WORKTREE_BASE}/"
    echo "  Cleanup:  git -C ${PROJECT_ROOT} worktree remove ${WORKTREE_BASE}/issue-<N>"
    echo ""
fi

echo "View results:  ls ${RUN_DIR}/issue-*/results.md"
echo "Ask Claude:    Check progress on ${RUN_DIR}"
